name: 'AUTOSAR CI'

on:
  workflow_dispatch:
  push:
    branches:
      - '**' 
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  # Dependencies:
  #   runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
  #   steps:

  Build:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Make build directory
        run: mkdir build
        
      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Install gcovr
        run: pip install gcovr

      - name: Create cmake configuration
        working-directory: build
        run: cmake ..

      - name: Build
        working-directory: build
        run: make all

  Linters:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run cppcheck
        uses: deep5050/cppcheck-action@v3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          other_options: --addon=cert

      - name: Archive cppcheck results
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-report
          path: cppcheck_report.txt

  UTs:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Make build directory
        run: mkdir build

      - name: Create cmake configuration
        working-directory: build
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug ..  -Dtest=ON

      - name: Build and Run UTs
        working-directory: build
        run: make gTests_all
             ./gTests_all --gtest_output=xml:./UTs_report.xml

      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3.7.0
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/UTs_report.xml'


#      - name: Archive coverage results
#        uses: actions/upload-artifact@v3
#        with:
#          name: code-coverage-report
#          path: build/coverage_report/

      # - name: Code Coverage Summary Report
      #   uses: irongut/CodeCoverageSummary@v1.3.0
      #   with:
      #     filename: build/coverage_report.xml
